### PR TITLE
English

### LINKED ISSUE #21: Change his to their
When switching between enderchest and inventory, it says "open his ender chest/inventory". Please change it to be "open their ender chest/inventory"

### PR DESCRIPTION
**Pull request by ManInMyVan**
I just need to know if "for animals that are tamed, you will also know it" means if an animal is tamed, who tamed the animal, or all tamed animals of a player.

Closes #21

### CODE REVIEW

**Comment by DailyCraft** [comment]
It's "if an animal is tamed, who tamed the animal"

**Comment by ManInMyVan** [comment]
The GitHub repository description should be `Open and modify the inventory of entities and players, and the ender chest of the players, online or not!`, to my knowledge I cannot change that in a commit.

**Comment by ManInMyVan** [comment]
Also, are there any other files that have English displayed to the user? (Seen files: /README.md, /pom.xml,  /main/src/main/resources/plugin.yml, /main/src/main/resources/config.yml, /main/src/main/resources/lang/en_us.json, & /LICENSE seems to be written by GitHub, so there shouldn't be anything there.)

**Comment by DailyCraft** [comment]
there are texts in this file https://github.com/DailyCraft/AdvancedSpyInventory/blob/master/main/src/main/java/mc/dailycraft/advancedspyinventory/Main.java and otherwise there is some in the wiki but it cannot be modified in a pull request

**Comment by ManInMyVan** [comment]
For the wiki, what do you mean by
`The last plugin version support Minecraft from 1.11 to the latest version.`?

**Comment by DailyCraft** [comment]
I mean that the latest version of the plugin supports from version 1.11 to the latest version of Minecraft

**Comment by ManInMyVan** [comment]
Wiki home page:
```
Welcome to the AdvancedSpyInventory wiki!

AdvancedSpyInventory supports Minecraft 1.11+.

This wiki contains documentation for:

- Commands
- Permissions
- The translation system
```

**Comment by ManInMyVan** [comment]
Ypu can merge this pr now.

**Review by DailyCraft — COMMENTED** [review]
In README.md, replace lines 4 to 7 by (you can modify it a little if you want):
```md
AdvancedSpyInventory allows you to see the inventory of players, but it also provides **different functionality** which makes it all the more useful.

These features are:
- Open the **inventory** of **online and offline** players
- Open the **ender chest** of **online and offline** players
- View and modify the **player's characteristics**, whether online or not, such as their life, location, experience, hunger, etc.
- View **the equipment of entities**
- Get and modify the **characteristics of entities**, such as knowing who tamed a tameable animal, the color of sheeps, the profession of villagers, etc.
- Open **the inventory of entities** as for villagers, enderman, etc.
```

**Comment by ManInMyVan** [comment]
> In README.md, replace lines 4 to 7 by (you can modify it a little if you want):
> ```md
> AdvancedSpyInventory allows you to see the inventory of players, but it also provides **different functionality** which makes it all the more useful.
> 
> These features are:
> - Open the **inventory** of **online and offline** players
> - Open the **ender chest** of **online and offline** players
> - View and modify the **player's characteristics**, whether online or not, such as their life, location, experience, hunger, etc.
> - View **the equipment of entities**
> - Get and modify the **characteristics of entities**, such as knowing who tamed a tameable animal, the color of sheeps, the profession of villagers, etc.
> - Open **the inventory of entities** as for villagers, enderman, etc.
> ```

Those lines don't seem to be in the readme.md yet. Here's the corrected version.

```md
AdvancedSpyInventory allows you to see the inventory of players, and provides **different functionality** which makes it all the more useful.

These features are:
- Open the **inventory** of **online and offline** players and entities 
- Open the **ender chest** of **online and offline** players
- View and modify the **stats** of **online and offline** players, such as health, location, experience, hunger, etc.
- View and modify **the equipment of entities**
-  View and modify the **properties of entities**, such as who tamed an entity, sheep's wool color, profession of villagers, etc.
> ```

**Comment by DailyCraft** [comment]
I didn't explain myself well: I think this is a better presentation for the mod than the few current lines, so delete lines 4 to 7 and replace them with this

**Comment by DailyCraft** [comment]
Are you ok with the new presentation or do you want to change something?

**Comment by ManInMyVan** [comment]
> Are you ok with the new presentation or do you want to change something?

Sorry for the late reply, but it seems like lines 4 - 12 in readme.md are the same as the ones you gave me here

> In README.md, replace lines 4 to 7 by (you can modify it a little if you want):
> ```md
> AdvancedSpyInventory allows you to see the inventory of players, but it also provides **different functionality** which makes it all the more useful.
> 
> These features are:
> - Open the **inventory** of **online and offline** players
> - Open the **ender chest** of **online and offline** players
> - View and modify the **player's characteristics**, whether online or not, such as their life, location, experience, hunger, etc.
> - View **the equipment of entities**
> - Get and modify the **characteristics of entities**, such as knowing who tamed a tameable animal, the color of sheeps, the profession of villagers, etc.
> - Open **the inventory of entities** as for villagers, enderman, etc.
> ```

And not the ones I gave back

> Those lines don't seem to be in the readme.md yet. Here's the corrected version.

> ```md
> AdvancedSpyInventory allows you to see the inventory of players, and provides **different functionality** which makes it all the more useful.

> These features are:
> - Open the **inventory** of **online and offline** players and entities 
> - Open the **ender chest** of **online and offline** players
> - View and modify the **stats** of **online and offline** players, such as health, location, experience, hunger, etc.
> - View and modify **the equipment of entities**
> - View and modify the **properties of entities**, such as who tamed an entity, sheep's wool color, profession of villagers, etc.
> ```

But other than that it's fine

**Pull request merged**
